src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Tribe;
use App\Entity\ToDoList;
use App\Entity\Documents;
use App\Entity\Repertoire;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;


/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Tribe::class, inversedBy="users", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $tribeId;

    /**
     * @ORM\Column(type="json")
     */
    private $role = [];

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $sexe;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $maidenName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="date")
     */
    private $birthDate;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $indPhone;

        /**
     * @ORM\OneToMany(targetEntity=Documents::class, mappedBy="user")
     */
    private $documents;

    /**
     * @ORM\OneToMany(targetEntity=ToDoList::class, mappedBy="user")
     */
    private $toDoLists;

    /**
     * @ORM\OneToMany(targetEntity=Repertoire::class, mappedBy="user")
     */
    private $repertoires;

        /**
     * @ORM\OneToMany(targetEntity=Liste::class, mappedBy="user")
     */
    private $listes;

    /**
     * @ORM\OneToMany(targetEntity=Council::class, mappedBy="user")
     */
    private $councils;

    public function __construct()
    {
		$this->documents = new ArrayCollection();
        $this->toDoLists = new ArrayCollection();
        $this->repertoires = new ArrayCollection();
        $this->listes = new ArrayCollection();
        $this->councils = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTribeId(): ?Tribe
    {
        return $this->tribeId;
    }

    public function setTribeId(?Tribe $tribeId): self
    {
        $this->tribeId = $tribeId;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $role = $this->role;
        $role[] = 'ROLE_USER';
        return array_unique($role);
    }

    public function setRoles(array $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }
    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    /**
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getMaidenName(): ?string
    {
        return $this->maidenName;
    }

    public function setMaidenName(?string $maidenName): self
    {
        $this->maidenName = $maidenName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(\DateTimeInterface $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(?int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getIndPhone(): ?string
    {
        return $this->indPhone;
    }

    public function setIndPhone(?string $indPhone): self
    {
        $this->indPhone = $indPhone;

        return $this;
    }

	/**
     * @return Collection|Documents[]
     */
    public function getDocuments(): Collection
    {
        return $this->documents;
    }

    public function addDocument(Documents $document): self
    {
        if (!$this->documents->contains($document)) {
            $this->documents[] = $document;
            $document->setUser($this);
			
        }

        return $this;
    }			


	/**
     * @return Collection|ToDoList[]
     */
    public function getToDoLists(): Collection
    {
        return $this->toDoLists;
    }

    public function removeDocument(Documents $document): self
    {
        if ($this->documents->removeElement($document)) {
            // set the owning side to null (unless already changed)
            if ($document->getUser() === $this) {
                $document->setUser(null);

            }
        }

        return $this;
    }

    public function addToDoList(ToDoList $toDoList): self
    {
        if (!$this->toDoLists->contains($toDoList)) {
            $this->toDoLists[] = $toDoList;
            $toDoList->setUser($this);
        }

        return $this;
    }

    public function removeToDoList(ToDoList $toDoList): self
    {
        if ($this->toDoLists->removeElement($toDoList)) {
            // set the owning side to null (unless already changed)
            if ($toDoList->getUser() === $this) {
                $toDoList->setUser(null);

            }
        }

        return $this;
    }

    /**
     * @return Collection|Repertoire[]
     */
    public function getRepertoires(): Collection
    {
        return $this->repertoires;
    }
    public function addRepertoire(Repertoire $repertoire): self
    {
        if (!$this->repertoires->contains($repertoire)) {
            $this->repertoires[] = $repertoire;
            $repertoire->setUser($this);
        }
        return $this;
    }
    public function removeRepertoire(Repertoire $repertoire): self
    {
        if ($this->repertoires->removeElement($repertoire)) {
            // set the owning side to null (unless already changed)
            if ($repertoire->getUser() === $this) {
                $repertoire->setUser(null);
            }
        }
        return $this;
    }

        /**
     * @return Collection|Liste[]
     */
    public function getListes(): Collection
    {
        return $this->listes;
    }

    public function addListe(Liste $liste): self
    {
        if (!$this->listes->contains($liste)) {
            $this->listes[] = $liste;
            $liste->setUser($this);
        }

        return $this;
    }

    public function removeListe(Liste $liste): self
    {
        if ($this->listes->removeElement($liste)) {
            // set the owning side to null (unless already changed)
            if ($liste->getUser() === $this) {
                $liste->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Council[]
     */
    public function getCouncils(): Collection
    {
        return $this->councils;
    }

    public function addCouncil(Council $council): self
    {
        if (!$this->councils->contains($council)) {
            $this->councils[] = $council;
            $council->setUser($this);
        }

        return $this;
    }

    public function removeCouncil(Council $council): self
    {
        if ($this->councils->removeElement($council)) {
            // set the owning side to null (unless already changed)
            if ($council->getUser() === $this) {
                $council->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Tribe;
use App\Repository\UserRepository;
use App\Repository\TribeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class UserController extends AbstractController
{
    /**
     * @Route("/user", name="user")
     */
    public function index(): Response
    {
        return $this->render('user/index.html.twig', [
            'controller_name' => 'UserController',
        ]);
    }


    /**
     * @Route("/gestion", name="gestion")
     * @Route("/gestion/{id}/remove", name="gestion_remove")
     */
    public function gestion(EntityManagerInterface $manager,UserRepository $userRepository, User $userRemove = null): Response
    {
        //clé étrangère
        $userByTribu = $this->getUser();

        // dump($userByTribu->getId());

        $userByTribus = $userRepository->findBy(array("tribeId" => $userByTribu->getTribeId()));
        $userRole = [];
        $userRole = $userByTribu->getRoles();

        dump($userRole);

        //suppression
        if($userRemove)
        {
            $manager->remove($userRemove);
            $manager->flush();
            $this->addFlash('success', "Le membre a bien été supprimé !");

            return $this->redirectToRoute('gestion');
        }

        return $this->render('user/gestion_user.html.twig', [
            'controller_name' => 'UserController',
            'usersBDD' => $userByTribus,
            'role' => $userRole
        ]);
    }
}

templates/user/gestion_user.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}User Gestion{% endblock %}

{% block body %}

    <h1 class=" text-center mx-auto title">Votre tribu</h1>

        {% for message in app.flashes('success') %}

        <div class="d-flex justify-content-center">
            <div class="alert alert-dark text-center col-5 my-2" role="alert">
            {{ message }}
            </div>
        </div>

        {% endfor %}    

    <div class="d-flex justify-content-center mb-2">
        <div class="accueil mb-3">
        </div>
    </div>
<div class="row d-flex justify-content-center align-items-center">

        {% for oneTribe in usersBDD %}
            {# {{ dump(oneTribe) }} #}

            <div class="cardUser d-flex flex-column justify-content-center align-items px-4 mx-2 mb-2">
                
                <h4 class="mb-0 titreUser">{{ oneTribe.firstName }}, {{ oneTribe.lastName }}</h4>
                <h5 class="mb-0 titreUser">{{ oneTribe.status }}</h5>
                    
                    <h5 class="mb-0">
                        {% if oneTribe.roles[0] == 'ROLE_SUPER_USER' %}
                            <p class="mb-0">Chef de Tribu</p>
                        {% else  %}
                            <p class="mb-0">Membre de la Tribu</p>
                        {% endif %}
                    </h5>

                    {% if is_granted('ROLE_SUPER_USER') %}
                    <div class="d-flex flex-row d-flex">
                        <a class="iconLinkUser" href="{{ path('gestion_remove' , {'id' : oneTribe.id}) }}"><i class="bi bi-trash"></i></a>
                        <a class="iconLinkUser" href="{{ path('addMember_edit' , {'id' : oneTribe.id}) }}"><i class="bi bi-pencil mx-2"></i></a>
                    </div>
                    {% endif %}
            </div>

        {% endfor %}
        {% if is_granted('ROLE_SUPER_USER') %}
        <div class="text-center my-5">
        <a class="" href="{{ path('addMember') }}"><input type="button" class="button" value="Ajouter Membre"></a>  
        </div>
        {% endif %}

    </div>

    <div>
    </div>

{% endblock %}

templates/user/index.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Tableau de bord{% endblock %}

{% block body %}

{# <h1 class="display-4 text-center my-4">BACKOFFICE</h1> #}
    <div class="row d-flex justify-content-center">
        <div class="dashboard d-flex justify-content-center align-items-center">
            <div class="text-center">
                <h4 class='title'>Bienvenue dans votre espace</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempo </p>
            </div>
        </div>
    </div>
    <div class="d-flex flex-wrap justify-content-center">
        <a href="{{ path('viewDocuments') }}" class="col-4 mb-3 me-3 btn widgetV">
            <h5 class="mt-3 fw-bold">Documents</h5>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempo </p>
            <h1><i class="bi bi-file-earmark-richtext"></i></h1>
        </a>
        <a href="{{ path('viewArticle') }}" class="col-4 mb-3 me-3 btn widgetO">
            <h5 class="mt-3 fw-bold">Courses</h5>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempo </p>
            <h1><i class="bi bi-basket"></i></h1>
        </a>
        <a href="{{ path('show') }}" class="col-4 mb-3 me-3 btn widgetV">
            <h5 class="mt-3 fw-bold">Répertoire</h5>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempo </p>
            <h1><i class="bi bi-journal-bookmark-fill"></i></h1>
        </a>
        
    </div>

    <div class="d-flex flex-wrap justify-content-center">
        <a href="{{ path('show_to_do_list') }}" class="col-4 mb-3 me-3 btn widgetO">
            <h5 class="mt-3 fw-bold">Mémos</h5>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempo </p>
            <h1><i class="bi bi-stickies"></i></h1>
        </a>
        <a href="{{ path('council') }}" class="col-4 mb-3 me-3 btn widgetV">
            <h5 class="mt-3 fw-bold">Réunion</h5>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempo </p>
            <h1 ><i class="bi bi-people"></i></h1>
        </a>
        
        <a href="{{ path('gestion') }}" class="col-4 mb-3 me-3 btn widgetO">
        {% if is_granted('ROLE_SUPER_USER') %} 
            <h5 class="mt-3 fw-bold">Gérer sa tribu</h5>
        {% else %}
        <h5 class="mt-3 fw-bold">Voir sa tribu</h5>
        {% endif %}
            
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempo </p>
            <h1 ><i class="bi bi-sliders"></i></h1>
        </a>
        
    </div>
    


{% endblock %}